### ISSUE TITLE
Dude, how to execute your code?

### ISSUE THREAD

**Issue by SpulaeMulae33** [Dopneer/MikuBomber#1]

**Comment by Dopneer** [comment]
Add phone into assets/numbers.txt (only Russian numbers, without +7)

node main.js

**Comment by SpulaeMulae33** [comment]
Error: Cannot find module 'puppeteer'
Require stack:
- /root/MikuBomber/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/root/MikuBomber/main.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/MikuBomber/main.js' ]
}

My error

**Comment by Dopneer** [comment]
npm install puppeteer

**Comment by Dopneer** [comment]
npm install puppeteer

**Comment by SpulaeMulae33** [comment]
again

**Comment by Dopneer** [comment]
> again

Again?

**Comment by Dopneer** [comment]
I'll load README in 5 min
